### ISSUE TITLE
LoginTokenAuth not compatible with Matomo 4

### ISSUE THREAD

**Issue by 65Q2M89mBVP53sCK** [HD-CMS/matomo-plugin-LoginTokenAuth#1]
The plugin is not compatible with the new Matomo 4 Major version.
After Installing/Upgrading the plugin is inactive and shows an warning in Plugins overview (LoginTokenAuth requires Piwik <4.0.0-b1)

**Comment by ant9000** [comment]
Simply change requirement to 5.0.0-b1 in plugin.json - the plugin in itself works.
Beware: in Matomo 4 the token is only accepted for users who cannot write anything.

**Comment by dhemeier** [comment]
Thanks for the testing with Matomo 4.X @ant9000 and the opened issue @65Q2M89mBVP53sCK 
I changed the plugin.json to allow usage of all 4.x Versions.

Should we need to refactor the plugin in order to allow tokenAuth for users with writeAccess?

Dennis

**Comment by ant9000** [comment]
Boy, you're fast! Thanks a bunch for the quick fix :+1: 

> Should we need to refactor the plugin in order to allow tokenAuth for users with writeAccess?

Not specifically needed for my use case, but it could be a nice plus. Just mentioning the fact in the README might be enough, though.
